
debug: true
spring:
#  mvc:
#    view:
#      suffix: .html

# 시큐리티 기본 설정
  security:
    user:
      name: user
      password: 1234


# 서버 기본 설정
server:
  error:
    # 에러 페이지 설정
    path:
    #기본 에러 페이지 off
    whitelabel:
      enabled: true


